config/routes.rb
Rails.application.routes.draw do
   devise_for :employees
   root 'users#index'
   resources :users do
    resources :loans
    resources :salaries, except: [:edit, :update] do
      resources :additional_earnings
      resources :additional_deductions
   end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_employee, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_employee!
    #load_and_authorize_resource 
    # load_resource


    
    def index 
        if current_employee.admin?
            @employees = Employee.all
            authorize @employees
        else
            @employees = Employee.where(employee_type: nil)
            authorize @employees
        end
    end
    
    def show
        # authorize! :read, current_user
        # if @employee.status = "resigned" || @employee.status = "terminated"
        #     render plain: "Employee not active!!"
        # end
    end
    
    def new
        @employee = Employee.new
    end
    
    def create
        @employee = Employee.new(employee_params)
        if @employee.save
            UserMailer.employee_added.deliver_later
            redirect_to users_path
        else 
            render :new
        end
    end
    
    def edit
            if @employee.status == "terminated" || @employee.status == "resigned"
            render plain: "Employee not active!!"
            end
            authorize @employee
    end
    
    def update
        if @employee.update(employee_params)
            authorize @employee
            flash[:notice]= "Employee information was edited"
            redirect_to users_path
        else 
            render "edit"
        end
    end
     def destroy
         @employee.delete
         flash[:notice]= "Employee information deleted"
         redirect_to users_path
    
     end
    private
    def employee_params
        params.require(:employee).permit(:email, :password, :name, :DOB, :BaseSalary, :status, :employee_type)
    end
    def set_employee
        @employee = Employee.find(params[:id])
    end
    
    end

app/views/users/edit.html.erb
<<div class= "container">

<%if @employee.errors.any?%>
    <ul>
     <%@employee.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
<%end%>
    </ul>
<%end%>
<div class= "row justify-content-center">
<div class= "col-12">
<%= form_with model:@employee, url:user_path do |f| %>
<div class="form-group row">

        <%=f.label :name, class: "col-2 col-form-label" %>
        <div class="col-8">
        <%=f.text_field :name, class: "form-control shadow rounded" %>
        </div>
</div>

    <div class="form-group row">
       <%=f.label :email , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :email, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :password , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :password, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :DOB , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :DOB, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :BaseSalary , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :BaseSalary, class:"form-control shawdow rounded" %>
    </div>
    </div>
       <%=f.select :status, [:active, :terminated, :resigned] ,class:"col-2 col-form-label"%>
    
        
    <div class="form-group row justify-content-center">
    <%=f.submit class: "btn btn-outline-dark btn-lg " %>
    </div>
<%end%>
</div>

<%=link_to "Return to Employees", users_path, class: "text-success" %>
<%=link_to "Add salary", new_user_salary_path(@employee.id),class: "text-success"%>
<%=link_to "New Loan", new_user_loan_path(@employee.id), class: "text-success"%>


</div>
</div>

app/views/users/index.html.erb
<div class="row justify-content-between" >
<div class="col-6">
<%= link_to 'New Employee', new_user_path,class:"btn btn-secondary" %>
</div>
<div class="col-6">
<div class= "end-0">
<%=button_to "Sign Out", destroy_employee_session_path, method: :delete, class:"btn btn-secondry" %>
</div>
</div>
</div>
<br/>
<div class="card mt-0">
<div class="card-header">
<h1 class="text-center">Employees</h1>
    
  </div>

<table class="table table-dark">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>DOB</th>
      <th>Base Salary</th>
      <th>Status</th>
      <th>Admin?</th>
      
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
    
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.DOB %></td>
        <td><%= employee.BaseSalary %></td>
        <td><%= employee.status %></td>
        <td><%= employee.employee_type%>
        
        
        <td><%= link_to 'Show', user_path(employee.id) , class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_user_path(employee),class:"btn btn-success" %></td>
      <%# <td><%= button_to 'Destroy', user_path(employee.id), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
        

      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

</div>
<br/>

app/views/users/new.html.erb
<<div class= "container">

<%if @employee.errors.any?%>
    <ul>
     <%@employee.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
<%end%>
    </ul>
<%end%>
<div class= "row justify-content-center">
<div class= "col-12">
<%= form_with model:@employee, url:users_path do |f| %>
<div class="form-group row">

        <%=f.label :name, class: "col-2 col-form-label" %>
        <div class="col-8">
        <%=f.text_field :name, class: "form-control shadow rounded" %>
        </div>
</div>

    <div class="form-group row">
       <%=f.label :email , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :email, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :password , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :password, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :DOB , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :DOB, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class="form-group row">
       <%=f.label :BaseSalary , class:"col-2 col-form-label"%>
       <div class="col-8">
       <%=f.text_field :BaseSalary, class:"form-control shawdow rounded" %>
    </div>
    </div>
    <div class= "form_check_feild">
  <%= f.label :employee_type, 'Is an HR account?', class:"form-check-label"%>

  <%= f.check_box :employee_type, {class:"form-check-input", type:"checkbox"},"true", "false" %>
  </div>
    <div class="form-group row justify-content-center">
    <%=f.submit class: "btn btn-outline-dark btn-lg " %>
    </div>
<%end%>
</div>

<%=link_to "Return to Employees", users_path, class: "text-success" %>
<%=link_to "Add new Salary", new_user_salary_path(:user_id), class: "text-success"%>


</div>
</div>

app/views/users/show.html.erb
<div class="container-sm">
<table class="table table-bordered table-sm">
  <tbody>
    <tr>
      <th scope="row">Employee ID</th>
      <td><%=@employee.id%></td>
    </tr>
    <tr>
      <th scope="row">Email</th>
      <td><%=@employee.email%></td>
    </tr>
    <tr>
      <th scope="row">Name</th>
      <td><%=@employee.name%></td>
  
    </tr>
    <tr>
      <th scope="row">DOB</th>
      <td><%=@employee.DOB%></td>
    
    </tr>
    <tr>
      <th scope="row">Base-Salary</th>
     <td><%=@employee.BaseSalary%></td>
      
    </tr>
    <tr>
      <th scope="row">Status</th>
     <td><%=@employee.status%></td>
      
    </tr>
    <tr>
      <th scope="row">SalaryDetails</th>
     <td><%=link_to "Salary details", user_salaries_path(@employee.id), class: "text-success"%></td>
      
    </tr>
    <tr>
      <th scope="row">View all Loans</th>
     <td><%=link_to "All Loans", user_loans_path(@employee.id), class: "text-success"%></td>
      
    </tr>
  </tbody>
</table>
<%=link_to "Return to Employees", users_path, class: "text-success" %>
<%=button_to "Sign Out", destroy_employee_session_path, method: :delete, class:"btn btn-secondry" %>
</div>